<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Contoso.Json" Version="10.0.0" />
    <PackageReference Include="Fabrikam.Identity" Version="1.2.0" />
  </ItemGroup>
</Project>
