<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Contoso.Json" Version="10.0.0" />
    <PackageReference Include="Fabrikam.Storage" Version="$(StorageVersion)" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
    <PackageReference Include="Fabrikam.MvcJson" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="Fabrikam.MvcJson" Version="8.0.0" />
  </ItemGroup>
</Project>
