<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Contoso.Json" Version="9.0.0" />
    <PackageReference Include="Contoso.Hosting" Version="$(HostingVersion)" />
  </ItemGroup>
</Project>
