<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <WarningsAsErrors>SYSLIB1050;SYSLIB1051;SYSLIB1052;SYSLIB1053;SYSLIB1055;SYSLIB1056;SYSLIB1057</WarningsAsErrors>
  </PropertyGroup>
</Project>
